// Generated module bindings for SpaceTimeDB
// Note: Normally these would be generated by the spacetime CLI
// This is a minimal implementation to make the client work

use spacetimedb_sdk::{
    table::{TableIter, TableWithPrimaryKey, TableWithoutPrimaryKey},
    Identity,
};
use crate::db_schema::{Conversation, Message};

// Extension trait for conversation table
pub trait ConversationTableExt {
    fn conversation_table(&self) -> ConversationTable;
}

// Extension trait for message table
pub trait MessageTableExt {
    fn message_table(&self) -> MessageTable;
}

// Implementation of conversation table
pub struct ConversationTable {
    inner: TableWithPrimaryKey<Conversation, u32>,
}

// Implementation of message table
pub struct MessageTable {
    inner: TableWithPrimaryKey<Message, u32>,
}

// Implementation methods for conversation table
impl ConversationTable {
    pub fn iter(&self) -> TableIter<Conversation> {
        self.inner.iter()
    }
    
    pub fn get(&self, id: u32) -> Option<&Conversation> {
        self.inner.get(&id)
    }
    
    pub fn count(&self) -> u64 {
        self.inner.count()
    }
}

// Implementation methods for message table
impl MessageTable {
    pub fn iter(&self) -> TableIter<Message> {
        self.inner.iter()
    }
    
    pub fn get(&self, id: u32) -> Option<&Message> {
        self.inner.get(&id)
    }
    
    pub fn count(&self) -> u64 {
        self.inner.count()
    }
}

// Make the tables accessible from DbConnection's 'db' field
#[derive(Clone)]
pub struct RemoteTables {
    inner: spacetimedb_sdk::table::Tables,
}

impl RemoteTables {
    pub fn new(tables: spacetimedb_sdk::table::Tables) -> Self {
        Self { inner: tables }
    }
}

impl ConversationTableExt for RemoteTables {
    fn conversation_table(&self) -> ConversationTable {
        ConversationTable {
            inner: TableWithPrimaryKey::new(&self.inner),
        }
    }
}

impl MessageTableExt for RemoteTables {
    fn message_table(&self) -> MessageTable {
        MessageTable {
            inner: TableWithPrimaryKey::new(&self.inner),
        }
    }
}

// Export extensions
pub use ConversationTableExt;
pub use MessageTableExt; 